db.url=jdbc:mysql://localhost:3306/train_booking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=YOUR_DB_USERNAME
db.password=YOUR_DB_PASSWORD

app.name=Console Train Booking App
app.admin.password=admin123

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

mail.sender.email=YOUR_EMAIL@gmail.com
mail.sender.password=YOUR_GMAIL_APP_PASSWORD
mail.sender.name=TrainBooking