import { useEffect, useState } from "react";
import { emailApi } from "../../api/emailApi";
import type { EmailOutboxResponse } from "../../types/email";

export default function AdminEmailsPage() {
  const [emails, setEmails] = useState<EmailOutboxResponse[]>([]);
  const [selectedEmail, setSelectedEmail] =
    useState<EmailOutboxResponse | null>(null);

  const [typeFilter, setTypeFilter] = useState<string>("ALL");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const loadEmails = async () => {
    try {
      const data = await emailApi.getAll();
      setEmails(data);
    } catch {
      setError("Could not load emails.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadEmails();
  }, []);

  const filteredEmails =
    typeFilter === "ALL"
      ? emails
      : emails.filter((email) => email.emailType === typeFilter);

  if (loading) {
    return <div className="card">Loading emails...</div>;
  }

  return (
    <div>
      <div className="page-header">
        <h1>Email outbox</h1>
        <p>View simulated emails generated by bookings and delays.</p>
      </div>

      {error && <p className="error">{error}</p>}

      <div className="card">
        <div className="filter-row">
          <div>
            <label>Email type</label>
            <select
              className="full-select"
              value={typeFilter}
              onChange={(event) => setTypeFilter(event.target.value)}
            >
              <option value="ALL">All</option>
              <option value="BOOKING_CONFIRMATION">
                Booking confirmation
              </option>
              <option value="DELAY_NOTIFICATION">Delay notification</option>
            </select>
          </div>

          <button className="btn-secondary" type="button" onClick={loadEmails}>
            Refresh
          </button>
        </div>
      </div>

      <div className="card mt">
        <h2>Emails</h2>

        {filteredEmails.length === 0 ? (
          <p>No emails found.</p>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Recipient</th>
                <th>Subject</th>
                <th>Type</th>
                <th>Status</th>
                <th>Created at</th>
                <th>Actions</th>
              </tr>
            </thead>

            <tbody>
              {filteredEmails.map((email) => (
                <tr key={email.id}>
                  <td>{email.id}</td>
                  <td>{email.recipientEmail}</td>
                  <td>{email.subject}</td>
                  <td>
                    <span
                      className={
                        email.emailType === "DELAY_NOTIFICATION"
                          ? "badge-warning"
                          : "badge-ok"
                      }
                    >
                      {email.emailType}
                    </span>
                  </td>
                  <td>
                    <span className="badge-neutral">{email.status}</span>
                  </td>
                  <td>{new Date(email.createdAt).toLocaleString()}</td>
                  <td>
                    <button
                      className="btn-secondary"
                      type="button"
                      onClick={() => setSelectedEmail(email)}
                    >
                      View body
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {selectedEmail && (
        <div className="card mt">
          <div className="email-body-header">
            <div>
              <h2>{selectedEmail.subject}</h2>
              <p>
                To: <strong>{selectedEmail.recipientEmail}</strong>
              </p>
            </div>

            <button
              className="btn-secondary"
              type="button"
              onClick={() => setSelectedEmail(null)}
            >
              Close
            </button>
          </div>

          <pre className="email-body">{selectedEmail.body}</pre>
        </div>
      )}
    </div>
  );
}